version: 2.1

orbs:
  node: circleci/node@4.1.0
  puppeteer: threetreeslight/puppeteer@0.1.2

jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - puppeteer/install
      - run:
          name: Yarn Test
          command: yarn run test

workflows:
  app_test:
    jobs:
      - test



