version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Yarn Test
          command: yarn run test

workflows:
  app_test:
    jobs:
      - test



