version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    docker:
      - image: 'cimg/node:lts-browsers'
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Tests
          command: yarn run test --silent --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit

workflows:
  test_app:
    jobs:
      - test
