version: 2.1

orbs:
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.2.3


jobs:
  prepare_dependencies:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: 'cimg/node:lts'
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./reports/
      JEST_JUNIT_OUTPUT_NAME: 'junit.xml'
      JEST_JUNIT_UNIQUE_OUTPUT_NAME: 'true'
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: yarn run test --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ./reports/
      - store_artifacts:
          path: ./reports/

  deploy:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - attach_workspace:
          at: .
      - heroku/install
      - heroku/deploy-via-git:
          maintenance-mode: true


workflows:
  test_app:
    jobs:
      - prepare_dependencies
      - test:
          requires:
            - prepare_dependencies
      - deploy:
          requires:
            - prepare_dependencies
            - test
